version: "3"
services:
  datastax-dse-server:
    container_name: commerce-test-db
    image: datastax/dse-server
    environment:
      DS_LICENSE: accept
    deploy:
      resources:
        limits:
          memory: 2G
  commerce-project:
    container_name: commerce-project
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # Required to keep console output open
    tty: true
    depends_on:
      - datastax-dse-server
